.TH bwctl 1 "$Date$"
." The first line of this file must contain the '"[e][r][t][v] line
." to tell man to run the appropriate filter "t" for table.
."
."	$Id$
."
."######################################################################
."#									#
."#			   Copyright (C)  2004				#
."#	     			Internet2				#
."#			   All Rights Reserved				#
."#									#
."######################################################################
."
."	File:		bwctl.1
."
."	Author:		Jeff Boote
."			Internet2
."
."	Date:		Sun Feb  8 16:01:25 MST 2004
."
."	Description:	
."
.SH NAME
bwctl \- Client application to request throughput tests.
.SH SYNOPSIS
.B bwctl 
[\fIoptions\fR] (\fI\-c recvhost | \-s sendhost\fR)
.SH DESCRIPTION
.B bwctl
is a command line client application that is used to initiate
.B iperf
throughput tests.
The application works by contacting
.B bwctld
daemons on both the receiving host and the sending host.
.SH OPTIONS
.SS Connection Arguements:
.TP
\fB\-A\fR \fIauthmode\fB
Specify the authentication modes the client is willing to use for
communication. \fIauthmode\fR should be set as a character string with
any or all of the characters "AEO". The modes are:
.RS
.IP \fBA\fR
[\fBA\fR]uthenticated. This encrypts the control connection.
.IP \fBE\fR
[\fBE\fR]ncrypted. The encrypts the control connection. If the test supports
encryption, this mode will additionally encrypt the test stream. (This is
currently done using iperf, which does not support encryption.)
.IP \fBO\fR
[\fBO\fR]pen. No encryption of any kind is done.
.PP
The client can specify all the modes it is willing to communicate with. The
most strict mode that both the server and the client are willing to speak
will be selected.
.IP Default:
"AEO"
.RE
.TP
\fB\-U\fR \fIusername\fR
Specify the username that is used to identify the AES key to use for
authenticated or encrypted modes.
.RS
.IP Default:
unset
.RE
.TP
\fB\-K\fR
Prompt the user for a \fIpassphrase\fR. This will be used to generate an AES
key for authenticated or encrypted modes. The \fB\-U\fR option MUST be
specified for this to be useful.
.RS
.IP Default:
unset
.RE
.TP
\fB\-k\fR \fIkeyfile\fR
Indicates that \fBbwctl\fR should use the AES key in \fIkeyfile\fR for
\fIusername\fB. \fIusername\fR must have a valid key in \fIkeyfile\fR.
\fIkeyfile\fR should have been generated using the \fBaespasswd(1)\fR
application.
.RS
.IP Default:
unset
.RE
.TP
\fB\-B\fR \fIsrcaddr\fR
Bind the local address of the client socket to \fIsrcaddr\fR. \fIsrcaddr\fR
can be specified using a DNS name or using standard textual notations for
the IP addresses.
.RS
.IP Default:
unspecified (wildcard address selection)
.RE
.SS Throughput Test Arguements:
(These are the arguements that are basically passed through to iperf. See
iperf equivalent args in most cases):
.TP
\fB\-i\fR \fIinterval\fR
Report interval (seconds)
.SH LIMITATIONS
Currently it is only possible to specify either the
.B iperf
sender or the
.B iperf
receiver on the command line. The local host is assumed to be the other
endpoint of the test.
.SH EXAMPLES
\fBaespasswd -f /usr/local/etc/bwctld.keys testuser\fP
.IP
Adds a key for the identity \fItestuser\fR. The user is prompted for
a passphrase. If the file does not exist, an error message will
be printed and no action will be taken.
.LP
\fBaespasswd -f /usr/local/etc/bwctld.keys -n testuser\fP
.IP
Creates the file before doing the same as above. If the file already
exists, an error message will be printed and no action will be taken.
.LP
\fBaespasswd -f /usr/local/etc/bwctld.keys -d testuser\fP
.IP
Deletes the identity \fItestuser\fR from the keyfile.
If the file does not exist, an error message will be printed.
.LP
.SH SECURITY CONSIDERATIONS
The keys in the \fIkeyfile\fR are not encrypted in any way. The security
of these keys is completely up to the security of the system and the
discretion of the system administrator.
.SH RESTRICTIONS
Currently \fIidentity\fR names are restricted to 16 characters, and passphrases
are limited to 1024 characters.
.SH SEE ALSO
.B owping(1)
,
.B owampd(1)
,
.B bwctl(1)
,
.B bwctld(1)
and the 
.B http://e2epi.internet2.edu/owamp
and
.B http://e2epi.internet2.edu/bwctl
web sites.
