#!/bin/env python

from os.path import dirname, realpath, sep, pardir
import sys
sys.path.insert(0, dirname(realpath(__file__)) + sep + pardir)

from bwctl.server.bwctl_server import bwctld

bwctld()
