#!/bin/env python

from os.path import dirname, realpath, sep, pardir
import sys
sys.path.append(dirname(realpath(__file__)) + sep + pardir)

from bwctl.client.bwctl_client import bwctl_client

bwctl_client()
