#!/usr/bin/env python

from os.path import dirname, realpath, sep, pardir
import sys
sys.path.insert(0, dirname(realpath(__file__)) + sep + pardir)

from bwctl.server.limits_parser_v1 import parse

if len(sys.argv) <  2:
    print "Please define a path to the limits file!"
    print "Usage: ./limits_converter <PATH-TO-LIMITS-FILE-V1>"
    sys.exit(1)
parse()
